version: '3'

services:
  static-web:
    build: ./static-web
    restart: always
    environment:
      - VIRTUAL_HOST=www.paraguide.uk,paraguide.uk,www.cager.name,cager.name
      - LETSENCRYPT_HOST=www.paraguide.uk,paraguide.uk,www.cager.name,cager.name
      - LETSENCRYPT_EMAIL=paul.cager@gmail.com
    volumes:
      - /var/www:/var/www:ro
    networks:
      - proxy-tier
      - default

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy-tier
    depends_on:
      - proxy

volumes:
  certs:
  vhost.d:
  html:

networks:
  proxy-tier:
