version: '3'

services:
  paraguide:
    image: paulcager/paraguide
    restart: always
    volumes:
            - ./secrets:/app/secrets:ro
            - club_cache:/app/club-cache
    command:
            [ "/app/paraguide", "--port", ":80" ]

  airspace-server:
    image: paulcager/gb-airspace
    restart: always
    ports:
      - 9092

  osheight-server:
    image: paulcager/gosdata
    restart: always
    ports:
      - 9091

  osgrid-server:
    image: paulcager/osgrid-server
    restart: always
    ports:
      - 9090

  caddy:
    image: caddy:2.3.0
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - /var/www:/var/www
      - ./secrets/key.txt:/var/www/www.cager.name/key.txt:ro

volumes:
  caddy_data:
  caddy_config:
  club_cache:

